affiliate_list_page:
    path: /
    controller: App\Controller\AffiliateController::getAffiliateListPage
    methods: GET

affiliate_card_page:
    path: /affiliate/{id}
    controller: App\Controller\AffiliateController::getAffiliateCardPage
    methods: GET
    requirements:
        id: '\d+'

update_affiliate:
    path: /affiliate/update
    controller: App\Controller\AffiliateController::updateAffiliate
    methods: POST

add_affiliate_page:
    path: /affiliate/add
    controller: App\Controller\AffiliateController::getAddAffiliatePage
    methods: GET

add_affiliate:
    path: /affiliate/add
    controller: App\Controller\AffiliateController::addAffiliate
    methods: POST

delete_affiliate:
    path: /affiliate/delete
    controller: App\Controller\AffiliateController::deleteAffiliate
    methods: POST