controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

affiliate_routes:
    resource: 'routes/affiliate.yaml'
    type: yaml

employee_routes:
    resource: 'routes/employee.yaml'
    type: yaml
